version: "3.8"

services:

  database:
    build:
      context: ./database
      dockerfile: Dockerfile
    environment:
      POSTGRES_DB_FILE: /run/secrets/secret_database_db
      POSTGRES_USER_FILE: /run/secrets/secret_database_user
      POSTGRES_PASSWORD_FILE: /run/secrets/secret_database_password
    networks:
      - database_adminer
      - database_io
    volumes:
      - database_volume:/var/lib/postgresql/data
    secrets:
      - secret_database_user
      - secret_database_password
      - secret_database_db

  email:
    build:
      context: ./email
      dockerfile: Dockerfile
    environment:
      EMAIL_ADDRESS: /run/secrets/secret_email_address
      EMAIL_PASSWORD: /run/secrets/secret_email_password
    secrets:
      - secret_email_address
      - secret_email_password

  io:
    build:
      context: ./io
      dockerfile: Dockerfile
    environment:
      DATABASE_USER: /run/secrets/secret_database_user
      DATABASE_PASSWORD: /run/secrets/secret_database_password
      DATABASE_DB: /run/secrets/secret_database_db
    secrets:
      - secret_database_user
      - secret_database_password
      - secret_database_db
    ports: 
      - 5000:5000
    volumes:
      - ./io:/app
    networks:
      - database_io

  adminer:
    image: adminer
    ports:
      - 8080:8080
    networks:
      - database_adminer

networks:
  database_adminer:
  database_io:

volumes:
  database_volume:

secrets:
  secret_database_user:
    file: ./secrets/database_user
  secret_database_password:
    file: ./secrets/database_password
  secret_database_db:
    file: ./secrets/database_db
  secret_email_address:
    file: ./secrets/email_address
  secret_email_password:
    file: ./secrets/email_password
